# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Navigation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navigation
  pod 'SnapKit', '~> 5.6.0'

end
